server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#okta:
#  oauth2:
#    issuer: https://dev-64958545.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oap8wbzmiArUQRaK5d7
#    client-secret: FyBl2GR7hwoyJ--3vEoH0UBh9hyHHKZSHhtzRfN7eKmGI4rblPy6sE0mZwL06YBl
#    scopes: openid, profile, email, offline_access